---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      labels:
        app: jenkins 
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
      - image: mohamedadeltaha/jenkins-with-docker-kubectl-gcloud:v1.0
        name: jenkins
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: pv 
        - mountPath: /var/run/docker.sock
          name: docker-socket
        resources: {}
      volumes:
      - name: pv 
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock