---
apiVersion: v1
kind: Service 
metadata:
  creationTimestamp: null 
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
  - name: port-1
    port: 8080
    protocol: TCP 
    targetPort: 8080
  - name: port-2
    port: 5000
    protocol: TCP 
    targetPort: 5000
  selector:
    app: jenkins 
  type: LoadBalancer 
status:
  loadBalancer: {}